project:
  name: nelishka
  version: 0.1.0

paths:
  data_dir: ./data
  models_dir: ./models
  logs_dir: ./logs

langgraph:
  default_graph: agent_flow
  auto_visualize: true
  recursion_limit: 10

rich_cli:
  theme: "dracula"
  verbose: true
